
[workspace]
exclude = ["python"]
members = [
    "task",
    "scheduler",
    "worker",
]

# cargo build --profile release-lto
[profile.release-lto]
codegen-units = 1
inherits = "release"
lto = true
